name: dart_movie_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.1
  envied: ^0.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mongo_dart: ^0.9.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  uuid: ^3.0.0
# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
